"""posts table

Revision ID: 689fcc21f1c6
Revises: 8a470f7e92ef
Create Date: 2023-06-09 19:02:21.413593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689fcc21f1c6'
down_revision = '8a470f7e92ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
